-- Migration: Add emoji column to locations table
-- Description: Add optional TEXT column to store a single emoji representing the location
-- Created: 2026-01-22

ALTER TABLE public.locations ADD COLUMN emoji text;

-- Add comment for documentation
COMMENT ON COLUMN public.locations.emoji IS 'Single emoji representing the location (e.g., 🍕, 🍜, ☕). Generated by OpenAI based on location details.';
